version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  e2e:
    extends:
      file: docker-compose.base.yml
      service: e2e
networks:
  laravue-net:
    driver: "bridge"