version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: laravue-frontend/app
    volumes:
      - .:/var/www/html
    networks:
      - lnet
    ports:
      - "${APP_PORT}:80"
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: laravue-frontend/node
    volumes:
      - .:/var/www/html
    networks:
      - lnet
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4445:4444'
      - '5901:5900'
    networks:
      default:
        aliases:
          - selenium
networks:
  lnet:
    driver: "bridge"