version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: laravue-frontend/app
    volumes:
      - .:/var/www/html
    networks:
      - laravue-net
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: laravue-frontend/node
    volumes:
      - .:/var/www/html
    networks:
      - laravue-net
  e2e:
    build:
      context: ./docker/e2e
      dockerfile: Dockerfile
    image: laravue-frontend/e2e
    volumes:
      - .:/tests
    networks:
      - laravue-net